/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef JUPITER_H
#define JUPITER_H

#ifdef _WIN32
#define JUPITER_EXPORT_FUNC __declspec(dllexport)
#else
#define JUPITER_EXPORT_FUNC
#endif

#include <cstdlib>
#include <cstdio>
#include <string>
#include <exception>

namespace Jupiter {
    class Jupiter {

    };
}

#endif
